//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zat.Tests.Runner.Common.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zat.Tests.Runner.Common.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDP client tests.
        /// </summary>
        public static string PdpClientTests {
            get {
                return ResourceManager.GetString("PdpClientTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pertinax6 tests.
        /// </summary>
        public static string Pertinax6Tests {
            get {
                return ResourceManager.GetString("Pertinax6Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime tests.
        /// </summary>
        public static string RuntimeTests {
            get {
                return ResourceManager.GetString("RuntimeTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run started..
        /// </summary>
        public static string TestRun_Started {
            get {
                return ResourceManager.GetString("TestRun_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run stopped..
        /// </summary>
        public static string TestRun_Stopped {
            get {
                return ResourceManager.GetString("TestRun_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run stopping..
        /// </summary>
        public static string TestRun_Stopping {
            get {
                return ResourceManager.GetString("TestRun_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test run did not start: the test assembly {0} changed and no longer holds these selected tests:
        ///{1}.
        /// </summary>
        public static string TestRun_TestEntitiesMissing_Format {
            get {
                return ResourceManager.GetString("TestRun_TestEntitiesMissing_Format", resourceCulture);
            }
        }
    }
}
