//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zat.Tests.Runner.TuiApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zat.Tests.Runner.TuiApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back_CommandText {
            get {
                return ResourceManager.GetString("Back_CommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time.
        /// </summary>
        public static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable debug mode.
        /// </summary>
        public static string EnableDebugMode_PromptText {
            get {
                return ResourceManager.GetString("EnableDebugMode_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report result to TestLink.
        /// </summary>
        public static string EnableTestLinkReporting_PromptText {
            get {
                return ResourceManager.GetString("EnableTestLinkReporting_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IDE install folder path: .
        /// </summary>
        public static string EnterIdeInstallFolderPath_PromptText {
            get {
                return ResourceManager.GetString("EnterIdeInstallFolderPath_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IDE release date:.
        /// </summary>
        public static string EnterIdeReleaseDate_PromptText {
            get {
                return ResourceManager.GetString("EnterIdeReleaseDate_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IDE version: .
        /// </summary>
        public static string EnterIdeVersion_PromptText {
            get {
                return ResourceManager.GetString("EnterIdeVersion_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter runtime release date:.
        /// </summary>
        public static string EnterRuntimeReleaseDate_PromptText {
            get {
                return ResourceManager.GetString("EnterRuntimeReleaseDate_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit_CommandText {
            get {
                return ResourceManager.GetString("Exit_CommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit app.
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_CommandText {
            get {
                return ResourceManager.GetString("Home_CommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HW assembly types.
        /// </summary>
        public static string HwAssemblyTypes_ChoiceText {
            get {
                return ResourceManager.GetString("HwAssemblyTypes_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDE install folder path: .
        /// </summary>
        public static string IdeInstallFolderPath_ChoiceText {
            get {
                return ResourceManager.GetString("IdeInstallFolderPath_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDE release date.
        /// </summary>
        public static string IdeReleaseDate_ChoiceText {
            get {
                return ResourceManager.GetString("IdeReleaseDate_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDE version.
        /// </summary>
        public static string IdeVersion_ChoiceText {
            get {
                return ResourceManager.GetString("IdeVersion_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up and down to reveal more choices.
        /// </summary>
        public static string MoveUpAndDownToReveal_HelpText {
            get {
                return ResourceManager.GetString("MoveUpAndDownToReveal_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in a date format.
        /// </summary>
        public static string MustBeDateFormat {
            get {
                return ResourceManager.GetString("MustBeDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No runtimes found under IDE install folder.
        /// </summary>
        public static string NoRuntimesFoundUnderIdeInstallFolder_Message {
            get {
                return ResourceManager.GetString("NoRuntimesFoundUnderIdeInstallFolder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        public static string NoShorten {
            get {
                return ResourceManager.GetString("NoShorten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be empty or does not exist.
        /// </summary>
        public static string PathCanNotBeEmpty_ErrorMessage {
            get {
                return ResourceManager.GetString("PathCanNotBeEmpty_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path doesn&apos;t exist.
        /// </summary>
        public static string PathDoesNotExist_ErrorMessage {
            get {
                return ResourceManager.GetString("PathDoesNotExist_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue ....
        /// </summary>
        public static string PressAnyKeyToContinue_Message {
            get {
                return ResourceManager.GetString("PressAnyKeyToContinue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [blue]&lt;space&gt;[/] to select an item, [green]&lt;enter&gt;[/] to accept.
        /// </summary>
        public static string PressSpaceToSelectItem {
            get {
                return ResourceManager.GetString("PressSpaceToSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run test.
        /// </summary>
        public static string RunTest_ChoiceText {
            get {
                return ResourceManager.GetString("RunTest_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtim release date.
        /// </summary>
        public static string RuntimeReleaseDate_ChoiceText {
            get {
                return ResourceManager.GetString("RuntimeReleaseDate_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime version.
        /// </summary>
        public static string RuntimeVersion_ChoiceText {
            get {
                return ResourceManager.GetString("RuntimeVersion_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected entities count.
        /// </summary>
        public static string SelectedEntities {
            get {
                return ResourceManager.GetString("SelectedEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected entities.
        /// </summary>
        public static string SelectedEntitiesCount {
            get {
                return ResourceManager.GetString("SelectedEntitiesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select HW assembly types.
        /// </summary>
        public static string SelectHwAssemblyType_PromptText {
            get {
                return ResourceManager.GetString("SelectHwAssemblyType_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting multiple HW02 options is not allowed.
        /// </summary>
        public static string SelectingMultipleHw02OptionsNotAllowed {
            get {
                return ResourceManager.GetString("SelectingMultipleHw02OptionsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select runtime version.
        /// </summary>
        public static string SelectRuntimeVersion_PromptText {
            get {
                return ResourceManager.GetString("SelectRuntimeVersion_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select test cases.
        /// </summary>
        public static string SelectTestCases_ChoiceText {
            get {
                return ResourceManager.GetString("SelectTestCases_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select test cases.
        /// </summary>
        public static string SelectTestCases_PromptText {
            get {
                return ResourceManager.GetString("SelectTestCases_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select test suites.
        /// </summary>
        public static string SelectTestSuites_ChoiceText {
            get {
                return ResourceManager.GetString("SelectTestSuites_ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select testsuites.
        /// </summary>
        public static string SelectTestSuites_PromptText {
            get {
                return ResourceManager.GetString("SelectTestSuites_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select testsuites to select testcases from.
        /// </summary>
        public static string SelectTestSuitesToSelectTestCases_PromptText {
            get {
                return ResourceManager.GetString("SelectTestSuitesToSelectTestCases_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_CommandText {
            get {
                return ResourceManager.GetString("Settings_CommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop test.
        /// </summary>
        public static string StopTest_CommandText {
            get {
                return ResourceManager.GetString("StopTest_CommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test entities.
        /// </summary>
        public static string TestEntities {
            get {
                return ResourceManager.GetString("TestEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result #{0} ({1}).
        /// </summary>
        public static string TestResultHeader_Format {
            get {
                return ResourceManager.GetString("TestResultHeader_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors, Failures and Warnings.
        /// </summary>
        public static string TestRunReport_ErrorsFailuresWarnings_SectionHeader {
            get {
                return ResourceManager.GetString("TestRunReport_ErrorsFailuresWarnings_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TestRunReport_Label_Error {
            get {
                return ResourceManager.GetString("TestRunReport_Label_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit.
        /// </summary>
        public static string TestRunReport_Label_Explicit {
            get {
                return ResourceManager.GetString("TestRunReport_Label_Explicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string TestRunReport_Label_Failed {
            get {
                return ResourceManager.GetString("TestRunReport_Label_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored.
        /// </summary>
        public static string TestRunReport_Label_Ignored {
            get {
                return ResourceManager.GetString("TestRunReport_Label_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string TestRunReport_Label_Invalid {
            get {
                return ResourceManager.GetString("TestRunReport_Label_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string TestRunReport_Label_Skipped {
            get {
                return ResourceManager.GetString("TestRunReport_Label_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string TestRunReport_Label_Warning {
            get {
                return ResourceManager.GetString("TestRunReport_Label_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string TestRunReport_Status_Failed {
            get {
                return ResourceManager.GetString("TestRunReport_Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconclusive.
        /// </summary>
        public static string TestRunReport_Status_Inconclusive {
            get {
                return ResourceManager.GetString("TestRunReport_Status_Inconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string TestRunReport_Status_Passed {
            get {
                return ResourceManager.GetString("TestRunReport_Status_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string TestRunReport_Status_Skipped {
            get {
                return ResourceManager.GetString("TestRunReport_Status_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string TestRunReport_Status_Unknown {
            get {
                return ResourceManager.GetString("TestRunReport_Status_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string TestRunReport_Status_Warning {
            get {
                return ResourceManager.GetString("TestRunReport_Status_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string TestRunReport_Summary_Duration {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string TestRunReport_Summary_EndTime {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string TestRunReport_Summary_Errors {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit.
        /// </summary>
        public static string TestRunReport_Summary_Explicit {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Explicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string TestRunReport_Summary_Failed {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Tests.
        /// </summary>
        public static string TestRunReport_Summary_FailedTests {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_FailedTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failures.
        /// </summary>
        public static string TestRunReport_Summary_Failures {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Failures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored.
        /// </summary>
        public static string TestRunReport_Summary_Ignored {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconclusive.
        /// </summary>
        public static string TestRunReport_Summary_Inconclusive {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Inconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string TestRunReport_Summary_Invalid {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string TestRunReport_Summary_Other {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall result.
        /// </summary>
        public static string TestRunReport_Summary_OverallResult {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_OverallResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string TestRunReport_Summary_Passed {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string TestRunReport_Summary_Seconds {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Run Summary.
        /// </summary>
        public static string TestRunReport_Summary_SectionHeader {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string TestRunReport_Summary_Skipped {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped Tests.
        /// </summary>
        public static string TestRunReport_Summary_SkippedTests {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_SkippedTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string TestRunReport_Summary_StartTime {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Count.
        /// </summary>
        public static string TestRunReport_Summary_TestCount {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_TestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string TestRunReport_Summary_Warnings {
            get {
                return ResourceManager.GetString("TestRunReport_Summary_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests Not Run.
        /// </summary>
        public static string TestRunReport_TestsNotRun_SectionHeader {
            get {
                return ResourceManager.GetString("TestRunReport_TestsNotRun_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselected.
        /// </summary>
        public static string Unselected {
            get {
                return ResourceManager.GetString("Unselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value required.
        /// </summary>
        public static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string YesShorten {
            get {
                return ResourceManager.GetString("YesShorten", resourceCulture);
            }
        }
    }
}
