<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Zat.Tests.Runner.Common.Net\Zat.Tests.Runner.Common.Net.csproj" />
	</ItemGroup>

</Project>
