<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Freemanke.Xmlrpc" Version="1.0.1" />
		<PackageReference Include="HtmlAgilityPack" Version="1.11.69" />
		<PackageReference Include="StreamJsonRpc" Version="2.25.29" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\DevKit.Core\DevKit.Core\DevKit.Core.csproj" />
		<ProjectReference Include="..\Zat.Tests.Runner.Common\Zat.Tests.Runner.Common.csproj">
			<PrivateAssets>all</PrivateAssets>
		</ProjectReference>
		<ProjectReference Include="..\Zat.Z2xxTests.Common\Zat.Z2xxTests.Common.csproj" />
	</ItemGroup>

</Project>
